# Generated by Django 3.0.5 on 2020-11-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_permission_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartID', models.IntegerField()),
                ('qr_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catID', models.IntegerField()),
                ('catName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentID', models.IntegerField()),
                ('comment', models.TextField()),
                ('customerID', models.IntegerField()),
                ('customerEmail', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.IntegerField()),
                ('itemName', models.CharField(max_length=20)),
                ('itemDes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onlinePaymentID', models.IntegerField()),
                ('cardNo', models.IntegerField()),
                ('cartType', models.CharField(max_length=10)),
                ('exp_Date', models.DateField()),
                ('transaction_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentID', models.IntegerField()),
                ('paymentMethod', models.CharField(max_length=10)),
                ('paymentDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateNo', models.IntegerField()),
                ('customerEmail', models.CharField(max_length=30, null=True)),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCatID', models.IntegerField()),
                ('subCatName', models.CharField(max_length=20)),
            ],
        ),
    ]
